### ISSUE TITLE
Weird cropping of body text

### ISSUE THREAD

**Issue by neurosnap** [michigan-com/newsfetch#19]
http://brevity.detroitnow.io/?articleId=73860580

http://www.battlecreekenquirer.com/story/news/local/2015/10/13/emmett-street-lane-blocked-repair/73860580/

<img width="1375" alt="screen shot 2015-10-13 at 4 37 53 pm" src="https://cloud.githubusercontent.com/assets/1940365/10467622/ccbe4f86-71c8-11e5-9421-4e352751ac5e.png">

**Comment by andreyvit** [comment]
Lol I know what's wrong.

Pop quiz: what false positives do you get when using `s.ToUpper() == s` as a test for uppercase strings?

**Comment by migreva** [comment]
"" == "" ?

**Comment by andreyvit** [comment]
Cool, failing article links are very useful.

**Comment by andreyvit** [comment]
Cool, failing article links are very useful.
