### ISSUE TITLE
Better Handling of bullet lists

### ISSUE THREAD

**Issue by neurosnap** [michigan-com/newsfetch#24]
https://api.michigan.com/v1/article/75895322/

http://www.lansingstatejournal.com/story/news/local/2015/11/17/lansing-lsj-storytelling/75895322/

**Comment by neurosnap** [comment]
http://thepul.se/article/79865168/
http://usatoday.com/story/news/2016/02/05/5-craziest-crimes-of-the-week/79865168/

**Comment by migreva** [comment]
Unique situation: this list is in a bunch of <p> tags, none of which have a period to terminate the string. So the summarizer treats the list as one long ass sentence


http://thepul.se/article/81268900/
http://www.usatoday.com/story/money/2016/03/03/sports-authority-store-closure-list/81268900/
