### ISSUE TITLE
Invalid UTF-8 character detected in mongo

### ISSUE THREAD

**Issue by neurosnap** [michigan-com/newsfetch#25]
We just ran into an error tonight that was crashing our summarizer.  It looks like the document has some invalid utf-8 characters.  I have not pinpointed the document that has caused the error yet but we need to think about how to properly sanitize data before committing it to mongo.

```
Nov 20 02:11:40 384664-snakevm supervisord: brevity   File "/srv/sites/brevity/app.py", line 94, in process_newsfetch_articles
Nov 20 02:11:40 384664-snakevm supervisord: brevity     results = process_article_summaries(mongo.db)
Nov 20 02:11:40 384664-snakevm supervisord: brevity   File "/srv/sites/brevity/summary.py", line 45, in process_article_summaries
Nov 20 02:11:40 384664-snakevm supervisord: brevity     for article in articles:
Nov 20 02:11:40 384664-snakevm supervisord: brevity   File "/srv/virtualenvs/brevity/lib/python3.4/site-packages/pymongo/cursor.py", line 1046, in next
Nov 20 02:11:40 384664-snakevm supervisord: brevity     if len(self.__data) or self._refresh():
Nov 20 02:11:40 384664-snakevm supervisord: brevity   File "/srv/virtualenvs/brevity/lib/python3.4/site-packages/pymongo/cursor.py", line 970, in _refresh
Nov 20 02:11:40 384664-snakevm supervisord: brevity     self.__batch_size))
Nov 20 02:11:40 384664-snakevm supervisord: brevity   File "/srv/virtualenvs/brevity/lib/python3.4/site-packages/pymongo/cursor.py", line 871, in __send_message
Nov 20 02:11:40 384664-snakevm supervisord: brevity     codec_options=self.__codec_options)
Nov 20 02:11:40 384664-snakevm supervisord: brevity   File "/srv/virtualenvs/brevity/lib/python3.4/site-packages/pymongo/helpers.py", line 133, in _unpack_response
Nov 20 02:11:40 384664-snakevm supervisord: brevity     result["data"] = bson.decode_all(response[20:], codec_options)
Nov 20 02:11:40 384664-snakevm supervisord: brevity bson.errors.InvalidBSON: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte
```

**Comment by travelinreid** [comment]
Is this at all similar to the issue Andrey had with UTF-8 encoding? (Mac app, maybe?)

Reid Williams
@travelinreid

**Comment by neurosnap** [comment]
Probably.

**Comment by andreyvit** [comment]
But question is, how did it make it to Mongo? Does go not check for strings validity? I mean, it's strange that mgo would be able to write an incorrect string, but would choke when reading it, and it's also strange that Go allows you to produce an incorrect string in the first place.

**Comment by neurosnap** [comment]
The summarizer is currently written in python.  So it goes from go -> mongo -> python.

Still your questions remain valid, currently not sure how the mgo driver allowed invalid utf-8 data to make it through.

First step is to find the document that has the invalid utf-8 characters.  Then we should probably create a unit test for it in golang.

**Comment by andreyvit** [comment]
Oh. Right. Didn't notice `.py`. :-)

Then I guess it means that Go allows arbitrary invalid bytes to make it into a string. Given that process-all is able to load all articles back, it seems that mgo has no problem serializing and deserializing these.
