### ISSUE TITLE
Summaries are getting removed when an article gets updated

### ISSUE THREAD

**Issue by neurosnap** [michigan-com/newsfetch#5]
Of course I'm overwriting the stupid summary whenever an article gets updated, so when an article gets updated it loses its summary temporarily before the summarizer activates again.

**Comment by andreyvit** [comment]
I don't like the whole idea of summarizer running later, because unsummarized articles show up very noticably. If you want to keep things split across processes, perhaps we should introduce a concept of a “processing stage”, and only return fully processed articles?

**Comment by neurosnap** [comment]
Me neither, I was sort of waiting for us to decide on which summarizer to use because one of the options is the golang implementation.  

We could probably use [exec](https://golang.org/pkg/os/exec/) to call the python script from newsfetch, but I feel like that is really messy.

Your idea would work as well.
